#!/sbin/busybox sh

# $1 - "android_logger"
# $2 - value=

if [ "a$2" != "a" ]; then
	android_logger=$2;

	case "${android_logger}" in
			0)
				echo "0" > /sys/module/logger/parameters/log_mode;
			;;
			1)
				echo "1" > /sys/module/logger/parameters/log_mode;
			;;
			2)
				echo "2" > /sys/module/logger/parameters/log_mode;
			;;
			3)
				echo "0" > /sys/module/logger/parameters/log_mode;
			;;
			*)
				android_logger=1;
			;;
	esac;

fi;

echo ${android_logger};
