#!/sbin/busybox sh

# $1 - "android_logger"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$android_logger";
else
	android_logger=$2;
	echo "$android_logger";
fi;

case "${android_logger}" in
	auto)
		# tweak is in cortex script, will be shut on screen off and loaded on screen on
	;;
	debug)
		# tweak is in cortex script, will be loaded and not be unloaded anymore
	;;
	disabled)
		# tweak is in cortex script, will be unloaded all the time
	;;
	*)
		android_logger=auto;
	;;
esac;
