#!/sbin/busybox sh

# $1 - "booster_off_time"
# $2 - value=
# Created By Alucard

if [ "a$2" != "a" ]; then
	booster_off_time=$2;

	echo "$booster_off_time" > /sys/module/synaptics_i2c_rmi/parameters/booster_off_time;
	echo "$booster_off_time" > /sys/module/gpio_keys/parameters/booster_off_time;
	echo "$booster_off_time" > /sys/module/cypress_touchkey_236/parameters/booster_off_time;
	echo "$booster_off_time" > /sys/module/mxts/parameters/booster_off_time;
fi;

echo ${booster_off_time};
