#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

PROFILE=`$BB cat /data/.alucard/.active.profile`;
CPU_VOLT_SWITCH=`$BB cat /data/.alucard/${PROFILE}.profile | $BB grep cpu_voltage_switch=on | $BB wc -l`;

if [ "a$3" == "a" ]; then
	evalcmd='eval "$BB echo \$CPUVOLT$2"';
	eval $evalcmd;
else
	evalcmd='eval "CPUVOLT$2=$3"';
	eval $evalcmd;
	evalcmd='eval "echo \$CPUVOLT$2"';
	eval $evalcmd;

	if [ "$CPU_VOLT_SWITCH" -eq "1" ]; then
		$BB echo "384000 $CPUVOLT15" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "486000 $CPUVOLT14" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "594000 $CPUVOLT13" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "702000 $CPUVOLT12" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "810000 $CPUVOLT11" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "918000 $CPUVOLT10" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1026000 $CPUVOLT9" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1134000 $CPUVOLT8" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1242000 $CPUVOLT7" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1350000 $CPUVOLT6" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1458000 $CPUVOLT5" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1566000 $CPUVOLT4" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1674000 $CPUVOLT3" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1782000 $CPUVOLT2" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
		$BB echo "1890000 $CPUVOLT1" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels;
	fi;
fi;
