#!/sbin/busybox sh

# $1 - "cpuhotplugging"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	cpuhotplugging=$2;

	case "${cpuhotplugging}" in
		1)
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_disable;
			if [ "$(ps | grep "mpdecision" | wc -l)" -le "1" ]; then
				/system/bin/start mpdecision
			fi;
		;;
		2)
			/system/bin/stop mpdecision;
			echo "1" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_disable;
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "1" > /sys/kernel/intelli_plug/intelli_plug_active;
			if [ "$(ps | grep /system/bin/thermal-engine | wc -l)" -ge "1" ]; then
				renice -n -20 -p $(pgrep -f "/system/bin/thermal-engine");
			fi;
		;;
		3)
			/system/bin/stop mpdecision;
			echo "1" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_disable;
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "1" > /sys/kernel/alucard_hotplug/hotplug_enable;
			if [ "$(ps | grep /system/bin/thermal-engine | wc -l)" -ge "1" ]; then
				renice -n -20 -p $(pgrep -f "/system/bin/thermal-engine");
			fi;
		;;
		4)
			/system/bin/stop mpdecision;
			echo "1" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_disable;
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "1" > /sys/module/msm_hotplug/msm_enabled;
			if [ "$(ps | grep /system/bin/thermal-engine | wc -l)" -ge "1" ]; then
				renice -n -20 -p $(pgrep -f "/system/bin/thermal-engine");
			fi;
		;;
		*)
			cpuhotplugging=3;
		;;
	esac;
fi;

echo ${cpuhotplugging};
