#!/sbin/busybox sh

# $1 - "dvfs_min_touch_limit"
# $2 - value=
# Created By Alucard

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	dvfs_min_touch_limit=$2;

	echo "$dvfs_min_touch_limit" > /sys/module/synaptics_i2c_rmi/parameters/min_touch_limit;
	echo "$dvfs_min_touch_limit" > /sys/module/cypress_touchkey_236/parameters/min_touch_limit;
	echo "$dvfs_min_touch_limit" > /sys/module/gpio_keys/parameters/min_touch_limit;
	echo "$dvfs_min_touch_limit" > /sys/module/mxts/parameters/min_touch_limit;
	echo "$dvfs_min_touch_limit" > /sys/module/rmi_fw_update/parameters/min_touch_limit;
fi;

echo ${dvfs_min_touch_limit};
