#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

FILEVAR=$2_iosched

if [ -z $4 ]; then
	evalcmd='eval $BB echo \$$FILEVAR'
	if [ "a`eval $evalcmd`" == "a" ]; then
		$BB sleep 2
		VAL=`$BB cat $3 | $BB sed -n -e '/\[[^]]/s/^[^[]*\[\([^]]*\)].*$/\1/p'`
		eval $FILEVAR=$VAL
		$BB echo $FILEVAR=$VAL >> $DEFAULT_PROFILE
	fi
else
	if [ -f $3 ];then
		echo $4 > $3
		eval $FILEVAR=`$BB cat $3 | $BB sed -n -e '/\[[^]]/s/^[^[]*\[\([^]]*\)].*$/\1/p'`
	else
		eval $FILEVAR=$4
	fi
fi

eval $BB echo \$$FILEVAR
