#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

# $1 - "lowmem_reserve"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	lowmem_reserve=$2;

case "${lowmem_reserve}" in
	relaxed)
		$BB echo "48 48" > /proc/sys/vm/lowmem_reserve_ratio;
	;;
	default)
		$BB echo "32 32" > /proc/sys/vm/lowmem_reserve_ratio;
	;;
	boosted)
		$BB echo "24 24" > /proc/sys/vm/lowmem_reserve_ratio;
	;;
	high_pressure)
		$BB echo "16 16" > /proc/sys/vm/lowmem_reserve_ratio;
	;;
	*)
		lowmem_reserve=boosted;
	;;
	esac;
fi;

$BB echo ${lowmem_reserve};
