#!/sbin/busybox sh

# $1 - "min_touch_limit_second"
# $2 - value=
# Created By Alucard

if [ "a$2" != "a" ]; then
	min_touch_limit_second=$2;

	echo "$min_touch_limit_second" > /sys/module/synaptics_i2c_rmi/parameters/min_touch_limit_second;
	echo "$min_touch_limit_second" > /sys/module/cypress_touchkey_236/parameters/min_touch_limit_second;
	echo "$min_touch_limit_second" > /sys/module/gpio_keys/parameters/min_touch_limit_second;
fi;

echo ${min_touch_limit_second};
