#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

# $1 - "mmc_mode"
# $2 - value=
# Created By Dorimanx
# Adapted to S4 By Alucard_24

if [ "a$2" != "a" ]; then
	mmc_mode=$2;

case "${mmc_mode}" in
	performance)
		if [ "$($BB cat /sys/devices/platform/msm_sdcc.1/mmc_host/mmc0/clk_scaling/scale_down_in_low_wr_load)" -eq "0" ]; then
			$BB echo "1" > /sys/devices/platform/msm_sdcc.1/mmc_host/mmc0/clk_scaling/scale_down_in_low_wr_load;
			$BB echo "1" > /sys/devices/platform/msm_sdcc.3/mmc_host/mmc1/clk_scaling/scale_down_in_low_wr_load;
			$BB echo "1" > /sys/devices/platform/msm_sdcc.2/mmc_host/mmc2/clk_scaling/scale_down_in_low_wr_load;
		fi;
	;;
	power_save)
		if [ "$($BB cat /sys/devices/platform/msm_sdcc.1/mmc_host/mmc0/clk_scaling/scale_down_in_low_wr_load)" -eq "1" ]; then
			$BB echo "0" > /sys/devices/platform/msm_sdcc.1/mmc_host/mmc0/clk_scaling/scale_down_in_low_wr_load;
			$BB echo "0" > /sys/devices/platform/msm_sdcc.3/mmc_host/mmc1/clk_scaling/scale_down_in_low_wr_load;
			$BB echo "0" > /sys/devices/platform/msm_sdcc.2/mmc_host/mmc2/clk_scaling/scale_down_in_low_wr_load;
		fi;
	;;
	*)
		mmc_mode=performance;
	;;
	esac;
fi;

$BB echo ${mmc_mode};
