#!/sbin/bb/busybox sh

# $1 - "msm_thermal"
# $2 - value=
# Created By Dorimanx

BB=/sbin/bb/busybox

# get values from profile
PROFILE=$($BB cat /data/.alucard/.active.profile);
. /data/.alucard/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	msm_thermal=$2;

	case "${msm_thermal}" in
		msm_temp)
			if [ "$($BB pgrep -f "/system/bin/thermal-engine" | $BB wc -l)" -eq "0" ]; then
				/system/bin/start thermal-engine;
			fi;
			if [ "$($BB cat /sys/module/msm_thermal/parameters/intelli_enabled)" == "Y" ]; then
				$BB echo "N" > /sys/module/msm_thermal/parameters/intelli_enabled;
			fi;
			$BB renice -n -17 -p "$($BB pgrep -f "/system/bin/thermal-engine")";
		;;
		intelli_temp)
			if [ "$($BB cat /sys/module/msm_thermal/parameters/intelli_enabled)" == "N" ]; then
				$BB echo "Y" > /sys/module/msm_thermal/parameters/intelli_enabled;
				$BB echo "$limit_temp_degC" > /sys/module/msm_thermal/parameters/limit_temp_degC;
				$BB echo "$core_limit_temp_degC" > /sys/module/msm_thermal/parameters/core_limit_temp_degC;
			fi;
			if [ "$($BB pgrep -f "/system/bin/thermal-engine" | $BB wc -l)" -ge "1" ]; then
				/system/bin/stop thermal-engine;
				/system/bin/stop thermal-engine;
				/system/bin/stop thermal-engine;
			fi;
		;;
		intelli_temp_dual)
			if [ "$($BB pgrep -f "/system/bin/thermal-engine" | $BB wc -l)" -eq "0" ]; then
				/system/bin/start thermal-engine;
			fi;
			if [ "$($BB cat /sys/module/msm_thermal/parameters/intelli_enabled)" == "N" ]; then
				$BB echo "Y" > /sys/module/msm_thermal/parameters/intelli_enabled;
				$BB echo "$limit_temp_degC" > /sys/module/msm_thermal/parameters/limit_temp_degC;
				$BB echo "$core_limit_temp_degC" > /sys/module/msm_thermal/parameters/core_limit_temp_degC;
			fi;
			$BB renice -n -17 -p "$(pgrep -f "/system/bin/thermal-engine")";
		;;
		*)
			msm_thermal=intelli_temp;
		;;
	esac;
fi;

$BB echo ${msm_thermal};
