#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

# $1 - "scaling_max_freq_cpu0"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$($BB cat /data/.b--b/.active.profile);
. /data/.b--b/"$PROFILE".profile;

if [ "$cortexbrain_cpu" == "on" ]; then
	if [ "a$2" != "a" ]; then
		scaling_max_freq_cpu0=$2;

		$BB echo "$scaling_max_freq_cpu0" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
	fi;
fi;

$BB echo ${scaling_max_freq_cpu0};
