#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

# $1 - "scaling_governor_cpu0"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$($BB cat /data/.alucard/.active.profile);
. /data/.alucard/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	scaling_governor_cpu0=$2;

	$BB echo "$scaling_governor_cpu0" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
fi;

$BB echo ${scaling_governor_cpu0};
