#!/sbin/bb/busybox sh

# SWAP
# Created by Dorimanx

# $1 - "swaptweaks"
# $2 - value=

BB=/sbin/bb/busybox

if [ "a$2" != "a" ]; then
	swaptweaks=$2;

	if [ -f /data/swapfile ]; then
		SWAP_SIZE=$($BB ls -la /data/swapfile | $BB awk '{ print $5}');
	else
		SWAP_SIZE=0;
	fi;
	DATA_FREE=$($BB df | $BB grep data | $BB awk '{ print $3}');

	case "${swaptweaks}" in
		0)
			if [ -f /data/swapfile ]; then
				$BB swapoff /data/swapfile >/dev/null 2>&1;
				$BB rm /data/swapfile;
			fi;
		;;
		256)
			if [ -f /data/swapfile ]; then
				$BB swapoff /data/swapfile >/dev/null 2>&1;
				if [ "$SWAP_SIZE" -lt "268435000" ] || [ "$SWAP_SIZE" -gt "288435456" ]; then
					$BB rm /data/swapfile;
					if [ "$DATA_FREE" -gt "524288" ]; then
						$BB dd if=/dev/zero of=/data/swapfile bs=1024 count=262144 >/dev/null 2>&1;
						$BB chown root:root /data/swapfile
						$BB chmod 0600 /data/swapfile
					fi;
				fi;
				if [ -f /data/swapfile ]; then
					$BB mkswap /data/swapfile
					$BB swapon /data/swapfile
				fi;
			else
				if [ "$DATA_FREE" -gt "524288" ]; then
					$BB dd if=/dev/zero of=/data/swapfile bs=1024 count=262144  >/dev/null 2>&1;
					$BB chown root:root /data/swapfile;
					$BB chmod 0600 /data/swapfile;
					$BB mkswap /data/swapfile
					$BB swapon /data/swapfile
				fi;
			fi;
		;;
		512)
			if [ -f /data/swapfile ]; then
				$BB swapoff /data/swapfile >/dev/null 2>&1;
				if [ "$SWAP_SIZE" -lt "536870000" ] || [ "$SWAP_SIZE" -gt "556870912" ]; then
					$BB rm /data/swapfile;
					if [ "$DATA_FREE" -gt "786432" ]; then
						$BB dd if=/dev/zero of=/data/swapfile bs=1024 count=524288 >/dev/null 2>&1;
						$BB chown root:root /data/swapfile;
						$BB chmod 0600 /data/swapfile;
					fi;
				fi;
				if [ -f /data/swapfile ]; then
					$BB mkswap /data/swapfile
					$BB swapon /data/swapfile
				fi;
			else
				if [ "$DATA_FREE" -gt "786432" ]; then
					$BB dd if=/dev/zero of=/data/swapfile bs=1024 count=524288  >/dev/null 2>&1;
					$BB chown root:root /data/swapfile;
					$BB chmod 0600 /data/swapfile;
					$BB mkswap /data/swapfile
					$BB swapon /data/swapfile
				fi;
			fi;
		;;
		*)
			swaptweaks=0;
		;;
	esac;
fi;
$BB echo ${swaptweaks};
