#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

# $1 - "uksm_gov_on"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	uksm_gov_on=$2;

case "${uksm_gov_on}" in
	full)
		$BB echo "full" > /sys/kernel/mm/uksm/cpu_governor;
	;;
	medium)
		$BB echo "medium" > /sys/kernel/mm/uksm/cpu_governor;
	;;
	low)
		$BB echo "low" > /sys/kernel/mm/uksm/cpu_governor;
	;;
	quiet)
		$BB echo "quiet" > /sys/kernel/mm/uksm/cpu_governor;
	;;
	*)
		uksm_gov_on=full;
	;;
	esac;
fi;

$BB echo ${uksm_gov_on};
