#!/sbin/busybox sh

if [ "a$2" != "a" ]; then
	usb_mode=$2;

	case "${usb_mode}" in
		default)
			# nothing to do here
		;;
		mass_storage-adb)
			/system/bin/setprop sys.usb.config mass_storage,adb;
			/system/bin/setprop persist.sys.usb.config mass_storage,adb;
			/system/bin/setprop sys.usb.state mass_storage,adb;
		;;
		mtp-adb)
			/system/bin/setprop sys.usb.config mtp,adb;
			/system/bin/setprop persist.sys.usb.config mtp,adb;
			/system/bin/setprop sys.usb.state mtp,adb;
		;;
		*)
			usb_mode="default";
		;;
	esac;
fi;

echo "${usb_mode}";
