#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

# $1 - "usb_keyboard"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	usb_keyboard=$2;

	case "${usb_keyboard}" in
		enable)
			$BB echo "0" > /sys/devices/virtual/android_usb/android0/enable;
			$BB echo "1" > /sys/module/g_android/parameters/usb_keyboard;
			$BB echo "9039" > /sys/class/android_usb/android0/idProduct;
			$BB echo "mtp,adb" > /sys/devices/virtual/android_usb/android0/functions;
			$BB echo "1" > /sys/devices/virtual/android_usb/android0/enable;
			$BB chown system.system /dev/hidg*;
			$BB chmod 777 /dev/hidg*
		;;
		disable)
			if [ "$($BB cat /sys/module/g_android/parameters/usb_keyboard)" == "1" ]; then
				$BB echo "0" > /sys/devices/virtual/android_usb/android0/enable;
				$BB echo "0" > /sys/module/g_android/parameters/usb_keyboard;
				$BB echo "633E" > /sys/class/android_usb/android0/idProduct;
				$BB echo "mtp:mtp,acm,diag,adb" > /sys/devices/virtual/android_usb/android0/functions;
				$BB echo "1" > /sys/devices/virtual/android_usb/android0/enable;
			fi;
		;;
		*)
			usb_keyboard=disable;
		;;
	esac;
fi;

$BB echo ${usb_keyboard};
