#!/sbin/busybox sh

(
	MEM_FREE=`free | grep Mem | awk '{ print $4 }'`;
	CALC_MEM=`echo $(($MEM_FREE/1024))M`;
	echo "FREE BEFORE $CALC_MEM" > /tmp/ram_clean;
	echo "PLEASE WAIT WORKING"  >> /tmp/ram_clean;
	chmod 777 /tmp/ram_clean;

	sync;
	sysctl -w vm.drop_caches=3 > /dev/null 2>&1;
	sysctl -w vm.drop_caches=1 > /dev/null 2>&1;
	MEM_FREE_AFTER=`free | grep Mem | awk '{ print $4 }'`;
	CALC_MEM_AFTER=`echo $(($MEM_FREE_AFTER/1024))M`;
	echo "FREE AFTER $CALC_MEM_AFTER" >> /tmp/ram_clean;
)&

sleep 3;
RAM_LOG=`cat /tmp/ram_clean`;
echo "$RAM_LOG";
