#!/sbin/bb/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

BB=/sbin/bb/busybox

if [ "a$2" == "a" ]; then
	$BB echo "$config_backup_restore";
else
	config_backup_restore=$2;
	$BB echo "$config_backup_restore";
fi;

if [ "$($BB pgrep -f "push-actions/config_backup_restore" | $BB wc -l)" -ge "3" ]; then
	$BB echo "Already working! dont push me!";
	exit 0;
fi;

PROFILE=$($BB cat /data/.b--b/.active.profile);

RELOAD_STWEAKS()
{
	$BB sync;
	am force-stop com.gokhanmoral.stweaks.app 2> /dev/null;
	am start -a android.intent.action.MAIN -n com.gokhanmoral.stweaks.app/.MainActivity 2> /dev/null;
	exit 0;
}

LOAD_NEW_SETTINGS()
{
	# get values from profile
	NEW_PROFILE=$($BB cat /data/.b--b/.active.profile);
	. /data/.b--b/"$NEW_PROFILE".profile;

	# Set new CPU freq based on profile.
	$BB echo "scaling_min_freq_cpu0" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;
	$BB echo "scaling_min_freq_cpu1" > /sys/devices/system/cpu/cpufreq/all_cpus/scaling_min_freq_cpu1;
	$BB echo "scaling_min_freq_cpu2" > /sys/devices/system/cpu/cpufreq/all_cpus/scaling_min_freq_cpu2;
	$BB echo "scaling_min_freq_cpu3" > /sys/devices/system/cpu/cpufreq/all_cpus/scaling_min_freq_cpu3;

	$BB echo "scaling_max_freq_cpu0" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
	$BB echo "scaling_max_freq_cpu1" > /sys/devices/system/cpu/cpufreq/all_cpus/scaling_max_freq_cpu1;
	$BB echo "scaling_max_freq_cpu2" > /sys/devices/system/cpu/cpufreq/all_cpus/scaling_max_freq_cpu2;
	$BB echo "scaling_max_freq_cpu3" > /sys/devices/system/cpu/cpufreq/all_cpus/scaling_max_freq_cpu3;
}

case "${config_backup_restore}" in
	1)
		$BB cp /data/.b--b/"$PROFILE".profile /data/.b--b/"$PROFILE".profile_backup;
		$BB cp /data/.b--b/"$PROFILE".profile /sdcard/"$PROFILE".profile_backup;
		$BB chmod 777 /data/.b--b/"$PROFILE".profile_backup;
		$BB echo "Backup of ${PROFILE} profile is Done!";
	;;
	2)
		(
			file2="/data/.b--b/${PROFILE}.profile_backup";

			# if someone full wipe the system, then use the profile_backup from sd-card
			if [ ! -e "$file2" ]; then
				file2="/sdcard/${PROFILE}.profile_backup";
			fi;

			if [ ! -e "$file2" ]; then
				$BB echo "You are using ${PROFILE} did you made backup for it??? if you made for other, switch to that profile first!";
				exit;
			fi;

			file1="/data/.b--b/${PROFILE}.profile";

			$BB echo "Restoring ${PROFILE} config file, wait for APP RELOAD";

			# read in file1->line1
			while read line1; do
				# split the config into variables where we find "="
				line1_1=$($BB echo "$line1" | $BB cut -f 1 -d '=');
				line1_2=$($BB echo "$line1" | $BB cut -f 2 -d '=');

				# grep the content from backup-file ...
				line2=$($BB grep "^${line1_1}\=" "$file2")
				# ... and also split into variables
				line2_1=$($BB echo "$line2" | $BB cut -f 1 -d '=');
				line2_2=$($BB echo "$line2" | $BB cut -f 2 -d '=');

				# compare config- and backup-file
				if [ "a${line1_1}" != "a${line2_1}" ]; then
					# nothing to do -> continue the loop
					continue;
				else
					# if backup-file has different values, then restore it
					if [ "a${line1_2}" != "a${line2_2}" ]; then
						if [ "${line2_2}" != "" ]; then
							$BB sed -i "s/${line1_1}=${line1_2}/${line2_1}=${line2_2}/" "$file1";
							$BB echo "edit: ${line1_1}=${line1_2} -> ${line2_1}=${line2_2}";
						fi;
					else
						# nothing to do -> continue the loop
						# $BB echo "not_edit: ${line1_1}=${line1_2} -> ${line2_1}=${line2_2}";
						continue;
					fi;
				fi;
			done < "$file1"

			# apply New STweaks settings
			$BB sh /res/uci.sh apply > /dev/null;
			RELOAD_STWEAKS;
		)&
	;;
	3)
		(
			$BB cp -a /res/customconfig/battery.profile /data/.b--b/;
			$BB echo "battery" > /data/.b--b/.active.profile;
			$BB echo "Restoring battery config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			LOAD_NEW_SETTINGS;
			RELOAD_STWEAKS;
		)&
	;;
	4)
		(
			$BB cp -a /res/customconfig/default.profile /data/.b--b/;
			$BB echo "default" > /data/.b--b/.active.profile;
			$BB echo "Restoring default config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			LOAD_NEW_SETTINGS;
			RELOAD_STWEAKS;
		)&
	;;
	5)
		(
			$BB cp -a /res/customconfig/performance.profile /data/.b--b/;
			$BB echo "performance" > /data/.b--b/.active.profile;
			$BB echo "Restoring performance config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			LOAD_NEW_SETTINGS;
			RELOAD_STWEAKS;
		)&
	;;
	6)
		(
			$BB cp -a /res/customconfig/extreme_battery.profile /data/.b--b/;
			$BB echo "extreme_battery" > /data/.b--b/.active.profile;
			$BB echo "Restoring extreme_battery config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			LOAD_NEW_SETTINGS;
			RELOAD_STWEAKS;
		)&
	;;
	7)
		(
			$BB cp -a /res/customconfig/extreme_performance.profile /data/.b--b/;
			$BB echo "extreme_performance" > /data/.b--b/.active.profile;
			$BB echo "Restoring extreme_performance config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			LOAD_NEW_SETTINGS;
			RELOAD_STWEAKS;
		)&
	;;
	*)
		echo "need input";
	;;
esac;
