#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
	CORTEX_CHECK=$($BB pgrep -f "/sbin/ext/cortexbrain-tune.sh" | $BB wc -l);
	if [ "$CORTEX_CHECK" != "0" ]; then
		$BB echo "SERVICE ONLINE";
	else
		$BB echo "SERVICE OFFLINE";
	fi;
)&
