#!/sbin/busybox sh

(
	/sbin/ext/cortexbrain-tune.sh apply_cpu update > /dev/null;

	local SYSTEM_GOVERNOR_PATH=$(find /sys/devices/system/cpu/cpufreq/all_cpus/scaling_governor_cpu*);
	local i="";
	local PREV_SYSTEM_GOVERNOR="";
	rm /data/.alucard/cpu_status;
	for i in $SYSTEM_GOVERNOR_PATH; do
		local SYSTEM_GOVERNOR=$(cat "$i");
		if [ "$(echo "$PREV_SYSTEM_GOVERNOR" | grep "$SYSTEM_GOVERNOR" | wc -l)" -lt "1" ]; then
			PREV_SYSTEM_GOVERNOR=$(printf "%s $SYSTEM_GOVERNOR" "$PREV_SYSTEM_GOVERNOR");
			if [ -d /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR ]; then
				cd /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/;
				echo "Tuning applied to '$SYSTEM_GOVERNOR' core!" >> /data/.alucard/cpu_status;
				grep "." * >> /data/.alucard/cpu_status;
				cd /;
			fi;
		fi;
	done;
)&
sleep 2;
CPU_LOG=`cat /data/.alucard/cpu_status`;
echo $CPU_LOG;
