#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

$BB rm -rf /data/crontab/*

CRON_STATUS=$($BB pidof crond | $BB wc -l);
if [ "$CRON_STATUS" -eq "1" ]; then
	$BB pkill -f crond;
	$BB sh /res/uci.sh crontab_switch on
	$BB echo "Reset Done! CRON is now enabled."
else
	$BB echo "Reset Done! CRON is now disabled."
fi;
