#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

if [ ! -e /data/crontab/cron-clear-file-cache ]; then
	$BB echo "no data" > /data/crontab/cron-clear-file-cache;
fi;
if [ ! -e /data/crontab/cron-ram-release ]; then
	$BB echo "no data" > /data/crontab/cron-ram-release;
fi;
if [ ! -e /data/crontab/cron-clear-ram-cache ]; then
	$BB echo "no data" > /data/crontab/cron-clear-ram-cache;
fi;
if [ ! -e /data/crontab/cron-ad-block-update ]; then
	$BB echo "no data" > /data/crontab/cron-ad-block-update;
fi;
if [ ! -e /data/crontab/cron-db-optimizing ]; then
	$BB echo "no data" > /data/crontab/cron-db-optimizing;
fi;
if [ ! -e /data/crontab/cron-mem-process-reclaim ]; then
	$BB echo "no data" > /data/crontab/cron-mem-process-reclaim;
fi;
if [ ! -e /data/crontab/cron-fstrim ]; then
	$BB echo "no data" > /data/crontab/cron-fstrim;
fi;
if [ ! -e /data/crontab/cron-clear-ram-cache ]; then
	$BB echo "no data" > /data/crontab/cron-clear-ram-cache;
fi;
if [ ! -e /data/crontab/cron-reset-systemui ]; then
	$BB echo "no data" > /data/crontab/cron-reset-systemui;
fi;
$BB chmod 777 /data/crontab/*
$BB cat /data/crontab/cron-clear-file-cache > /data/crontab/cron_log;
$BB echo "---" >> /data/crontab/cron_log;
$BB cat /data/crontab/cron-clear-ram-cache >> /data/crontab/cron_log;
$BB echo "---" >> /data/crontab/cron_log;
$BB cat /data/crontab/cron-reset-systemui >> /data/crontab/cron_log;
$BB echo "---" >> /data/crontab/cron_log;
$BB cat /data/crontab/cron-fstrim >> /data/crontab/cron_log;
$BB echo "---" >> /data/crontab/cron_log;
$BB cat /data/crontab/cron-ram-release >> /data/crontab/cron_log;
$BB echo "---" >> /data/crontab/cron_log;
$BB cat /data/crontab/cron-mem-process-reclaim >> /data/crontab/cron_log;
$BB echo "---" >> /data/crontab/cron_log;
$BB cat /data/crontab/cron-ad-block-update >> /data/crontab/cron_log;
$BB echo "---" >> /data/crontab/cron_log;
$BB cat /data/crontab/cron-clear-ram-cache >> /data/crontab/cron_log;
$BB echo "---" >> /data/crontab/cron_log;
$BB cat /data/crontab/cron-db-optimizing >> /data/crontab/cron_log;

# push all to one log.
CRON_LOG=$($BB cat /data/crontab/cron_log);
$BB echo "$CRON_LOG";
