#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
	if [ "$($BB pgrep -f "database_optimizing" |  $BB wc -l)" -le "5" ]; then
		$BB echo "";
		$BB echo "*********************************************";
		$BB echo "Optimizing and defragging your database files (*.db)";
		$BB echo "*********************************************";
		$BB echo "";

		for i in `/sbin/bb/busybox find /data -iname "*.db"`; do
			/system/xbin/sqlite3 $i 'VACUUM;';
			/system/xbin/sqlite3 $i 'REINDEX;';
		done;

		for i in `/sbin/bb/busybox find /sdcard -iname "*.db"`; do
			/system/xbin/sqlite3 $i 'VACUUM;';
			/system/xbin/sqlite3 $i 'REINDEX;';
		done;
	else
		echo "Database Optimizing already running, please wait.";
	fi;
)& 
