#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
	echo "/dev/block/vold/179:32" > /sys/devices/virtual/android_usb/android0/f_mass_storage/lun0/file;

	if [ -e /dev/block/vold/179:33 ]; then
		echo "/dev/block/vold/179:33" > /sys/devices/virtual/android_usb/android0/f_mass_storage/lun1/file;
	fi;
)&

echo "Try now to open usb drive/s.";
