#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
	if [ `$BB pgrep -f "fix_permissions" |  wc -l` \< 5 ]; then
		$BB echo "Fixing permissions started! please leave the phone alone for 3min, no need to reboot.!";
		/sbin/fix_permissions -l -r -v > /dev/null 2>&1;
	else
		$BB echo "fix_permissions still running, please wait";
	fi;
)&
