#!/sbin/busybox sh

/sbin/busybox fstrim -v /system > /data/.alucard/fstrim_log;
/sbin/busybox fstrim -v /data >> /data/.alucard/fstrim_log;
/sbin/busybox fstrim -v /cache >> /data/.alucad/fstrim_log;

fstrim_log=$(cat /data/.alucard/fstrim_log);

echo "$fstrim_log"

