#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

$BB fstrim -v /system > /data/.alucard/fstrim_log;
$BB fstrim -v /data >> /data/.alucard/fstrim_log;
$BB fstrim -v /cache >> /data/.alucad/fstrim_log;

fstrim_log=$($BB cat /data/.alucard/fstrim_log);

$BB echo "$fstrim_log"

