#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

#created by Dorimanx.

selinux_status=$(grep -c "enforcing=0" /proc/cmdline);

if [ "$selinux_status" -eq "0" ]; then
	$BB echo "SELinux set as Enforcing!";
else
	$BB echo "SELinux set as Permissive";
fi;
