#!/sbin/busybox sh

#created by Dorimanx.

selinux_status=$(grep -c "enforcing=0" /proc/cmdline);

if [ "$selinux_status" -eq "0" ]; then
	echo "SELinux set as Enforcing!";
else
	echo "SELinux set as Permissive";
fi;
