#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

if [ -e /data/data/com.af.synapse ]; then
	$BB echo "Starting Synapse APP"
	am start -a android.intent.action.MAIN -n com.af.synapse/.MainActivity > /dev/null;
else
	$BB echo "You dont have Synapse APP Installed."
fi;
