#!/sbin/bb/busybox sh

BB=/sbin/bb/busybox

WGET_CHECK1=`$BB ls -la /system/xbin/wget | wc -l`;
WGET_CHECK2=`$BB ls -la /system/bin/wget | wc -l`;
WGET_CHECK3=`$BB ls -la /system/wget/wget | wc -l`;

if [ "$WGET_CHECK1" -eq "1" ] || [ "$WGET_CHECK2" -eq "1" ] || [ "$WGET_CHECK3" -eq "1" ]; then

	TMPFILE=$($BB mktemp -t);
	$BB mount -o remount,rw /;

	DNS1=`getprop net.dns1`;
	DNS2=`getprop net.rmnet0.dns1`;
	DNS3=`getprop net.rmnet0.dns2`;

	$BB echo "nameserver 8.8.8.8" > /system/etc/resolv.conf;
	$BB echo "nameserver 4.4.8.8" >> /system/etc/resolv.conf;
	$BB echo "nameserver $DNS1" >> /system/etc/resolv.conf;
	$BB echo "nameserver $DNS2" >> /system/etc/resolv.conf;
	$BB echo "nameserver $DNS3" >> /system/etc/resolv.conf;

	TESTCONNECTION=`wget http://www.google.com -O $TMPFILE > /dev/null 2>&1`;
	if [ $? != 0 ]; then
		$BB echo "Problem: no internet connection! connect and try again";
	else
		(
			ntpd -n -q -p `$BB cat /system/etc/gps.conf | $BB grep NTP_SERVER | $BB cut -f 2 -d "="`;
		)&
		$BB echo "updated time via ntp";
	fi;

	$BB rm -f $TMPFILE;

	$BB mount -o remount,ro /system;
else
	echo "Your BusyBox is not supported! Update to latest";
fi;
